#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render studies/photoexcitation/REPORT.md from results.tsv.

The report is generated so that it cannot drift from the numbers. Markdown
rather than HTML for the same reason the oracle notes are: it diffs, it reviews,
and `--check` can tell whether it is stale without a browser.

Usage::

    python tools/study/render_report.py
    python tools/study/render_report.py --check   # fail if the committed file is stale

The table itself is produced by `cargo test --test photoexcitation` with
`XNDO_STUDY_WRITE=1`; this script never runs a calculation and never invents a
number. Anything here that is not read out of the TSV is prose.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
STUDY = os.path.join(ROOT, "studies", "photoexcitation")
RESULTS = os.path.join(STUDY, "results.tsv")
REPORT = os.path.join(STUDY, "REPORT.md")


def read_rows(path):
    with open(path, encoding="utf-8") as fh:
        lines = [l.rstrip("\n") for l in fh if not l.startswith("#")]
    header = lines[0].split("\t")
    rows = []
    for line in lines[1:]:
        if not line.strip():
            continue
        rows.append(dict(zip(header, line.split("\t"))))
    return rows


def molecules_in_order(rows):
    seen = []
    for row in rows:
        if row["molecule"] not in seen:
            seen.append(row["molecule"])
    return seen


def render(rows):
    out = []
    w = out.append
    w("<!-- Generated by tools/study/render_report.py from results.tsv. Do not edit. -->")
    w("")
    w("# What ZINDO/S-CIS does to photoexcitation")
    w("")
    w("Every number below is read out of `results.tsv`, which is written by")
    w("`cargo test --test photoexcitation`. Nothing here is transcribed by hand,")
    w("and nothing is compared against a literature value -- see **What this")
    w("study does not do**.")
    w("")

    singlets = [r for r in rows if r["spin"] == "singlet"]
    triplets = [r for r in rows if r["spin"] == "triplet"]
    names = molecules_in_order(rows)
    w("## The set")
    w("")
    w("{} molecules, {} singlet and {} triplet roots: {}.".format(
        len(names), len(singlets), len(triplets), ", ".join(names)))
    w("")
    w("Planar, C/N/O/H only, so every atom is inside the ZINDO/S s-p branch and")
    w("no result here is confounded by a missing parameter. The ring geometries")
    w("are regular polygons: the right idealisation for asking what the model")
    w("does with a state of a given symmetry, and the wrong one for comparing an")
    w("excitation energy with an experimental band maximum, which this study")
    w("does not do.")
    w("")

    w("## Lowest singlet per molecule")
    w("")
    w("| molecule | S1 / eV | f | polarisation | dipole change / D | T1 / eV | S1 - T1 / eV |")
    w("| --- | ---: | ---: | --- | ---: | ---: | ---: |")
    for name in names:
        s = [r for r in singlets if r["molecule"] == name]
        t = [r for r in triplets if r["molecule"] == name]
        s1, t1 = s[0], t[0]
        w("| {} | {:.3f} | {:.4f} | {} | {:.2f} | {:.3f} | {:.3f} |".format(
            name, float(s1["energy_ev"]), float(s1["oscillator"]), s1["polarisation"],
            float(s1["diff_dipole_debye"]), float(t1["energy_ev"]),
            float(s1["energy_ev"]) - float(t1["energy_ev"])))
    w("")

    dark = [r for r in singlets if r["polarisation"] == "dark"]
    oop = [r for r in singlets if r["polarisation"] == "out-of-plane"]
    w("## Polarisation")
    w("")
    w("Of {} singlet roots, {} are in-plane, {} out-of-plane and {} dark.".format(
        len(singlets), len(singlets) - len(dark) - len(oop), len(oop), len(dark)))
    w("")
    w("For a planar molecule this classification is exact rather than")
    w("approximate. Reflection in the molecular plane is a symmetry; pi orbitals")
    w("are odd under it and in-plane orbitals even, and of the dipole components")
    w("the two in-plane ones are even and the normal one odd. So a")
    w("parity-preserving excitation can only couple to the in-plane components")
    w("and a parity-changing one only to the normal component. A test asserts")
    w("that no root is polarised partly along both, and none is.")
    w("")
    w("Two readings that the table refuses, both of which a looser classifier")
    w("would make:")
    w("")
    w("* **dark is not n->pi\\***. Benzene's two lowest singlets are dark and both")
    w("  are pi->pi\\*; benzene has no lone pair at all.")
    w("* **out-of-plane is not n->pi\\*** either. Sigma orbitals are even under the")
    w("  reflection just as lone pairs are, so sigma->pi\\* is out-of-plane too.")
    w("  Ethene, with no lone pair, has such a root at 8.73 eV.")
    w("")
    w("And the limit of the approach: formaldehyde's n->pi\\* is A2 in C2v, which")
    w("spans no component of the dipole, so it is not out-of-plane polarised but")
    w("*completely* dark -- invisible to a measure built on the transition")
    w("dipole's direction. It is in the table at 3.187 eV, identifiable instead")
    w("by its 2.55 D difference dipole. That is why the table carries the")
    w("difference dipole beside the polarisation rather than instead of it.")
    w("")

    w("## The singlet-triplet gap separates the two state types on its own")
    w("")
    w("Nothing in the set-up sorts the molecules; this comes out of the")
    w("calculation. `S1 - T1` is twice the exchange integral over the hole and")
    w("particle orbitals, so it measures how much the two overlap -- large when")
    w("both live in the same pi system, small when the hole is a lone pair in the")
    w("molecular plane and the particle is a pi\\* orbital perpendicular to it.")
    w("")
    gaps = []
    for name in names:
        s1 = [r for r in singlets if r["molecule"] == name][0]
        t1 = [r for r in triplets if r["molecule"] == name][0]
        gaps.append((name, float(s1["energy_ev"]) - float(t1["energy_ev"]),
                     s1["polarisation"], float(s1["diff_dipole_debye"])))
    parity_changing = [g for g in gaps if g[2] == "out-of-plane" or g[3] > 1.0]
    parity_keeping = [g for g in gaps if g not in parity_changing]
    if parity_changing and parity_keeping:
        w("| S1 character | molecules | S1 - T1 / eV |")
        w("| --- | --- | ---: |")
        w("| hole and particle share the pi system | {} | {:.2f} to {:.2f} |".format(
            ", ".join(g[0] for g in parity_keeping),
            min(g[1] for g in parity_keeping), max(g[1] for g in parity_keeping)))
        w("| hole in the molecular plane, particle perpendicular | {} | {:.2f} to {:.2f} |".format(
            ", ".join(g[0] for g in parity_changing),
            min(g[1] for g in parity_changing), max(g[1] for g in parity_changing)))
        w("")
        w("The two ranges do not overlap: the smallest gap in the first group is")
        w("{:.2f} eV and the largest in the second is {:.2f} eV.".format(
            min(g[1] for g in parity_keeping), max(g[1] for g in parity_changing)))
        w("")

    w("## What this study does not do")
    w("")
    w("It does not compare a single excitation energy against a measured or")
    w("high-level-computed one, so it says nothing about how accurate ZINDO/S-CIS")
    w("is. That was deliberate twice over.")
    w("")
    w("The first reason is that the comparison needs reference data this")
    w("repository does not have. Transcribing a benchmark set from a paper is")
    w("real work with a real error rate, and the project's rule for reference")
    w("numbers -- two independently written parsers, both sides re-read and")
    w("compared -- exists because of it. Guessing at remembered values instead")
    w("would have produced a study-shaped object with no evidence in it.")
    w("")
    w("The second is that an accuracy number, on its own, would not have")
    w("separated the two errors that make it up: the CIS ansatz's, and the")
    w("semiempirical Hamiltonian's. Separating them needs a correlated method on")
    w("the same Hamiltonian, and post-HF is out of scope for v0.3.0. The natural")
    w("next step for this study is that decomposition, not a longer table.")
    w("")
    w("What is here instead is a set of measurements against things that are")
    w("known exactly -- an asymptotic form, a reflection symmetry, a variational")
    w("bound. Those need no external data and admit no tolerance argument.")
    w("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed report differs from a fresh render")
    args = ap.parse_args()

    text = render(read_rows(RESULTS))
    if args.check:
        if not os.path.exists(REPORT):
            print("REPORT.md is missing", file=sys.stderr)
            return 1
        with open(REPORT, encoding="utf-8") as fh:
            if fh.read().replace("\r\n", "\n") != text:
                print("REPORT.md is stale; rerun without --check", file=sys.stderr)
                return 1
        print("REPORT.md is up to date")
        return 0
    with open(REPORT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote {}".format(os.path.relpath(REPORT, ROOT)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
